#!/usr/bin/env ruby

require_relative "./squelcher"

begin
  first, *rest = ARGV
  if first == 'between'
    dates = Squelcher.new.between rest.join(" ")
  else
    dates = Squelcher.new.squelch ARGV.join(" ")
  end
rescue Squelcher::ParseError => e
  puts e.message
else
  puts dates.join(", ")
end
